CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(256) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     password VARCHAR(256) NOT NULL,
                                     CONSTRAINT UQ_USERS_EMAIL UNIQUE (email),
                                     CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subscribers (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                             user_id BIGINT NOT NULL,
                                             subscriber_id BIGINT NOT NULL,
                                             CONSTRAINT pk_subscribers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS friends (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           friend1_id BIGINT NOT NULL,
                                           friend2_id BIGINT NOT NULL,
                                           CONSTRAINT pk_friends PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS posts (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                             header VARCHAR(1000),
                                             description VARCHAR(4000),
                                             image bytea,
                                             imageContentType VARCHAR(256),
                                             created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                             author_id BIGINT,
                                             CONSTRAINT pk_posts PRIMARY KEY (id),
                                             CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS requests (
                                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                             initiator_id BIGINT,
                                             friend_id BIGINT,
                                             description VARCHAR(4000) NOT NULL,
                                             created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                             friendStatus VARCHAR (100) NOT NULL,
                                             reqStatus VARCHAR (100) NOT NULL,
                                             CONSTRAINT pk_requests PRIMARY KEY (id),
                                             CONSTRAINT FK_REQUESTS_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id),
                                             CONSTRAINT FK_REQUESTS_ON_INITIATOR FOREIGN KEY (friend_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS messages (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     text VARCHAR(4000),
                                     sent TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     sender_id BIGINT,
                                     receiver_id BIGINT,
                                     CONSTRAINT pk_messages PRIMARY KEY (id),
                                     CONSTRAINT FK_MESSAGES_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id),
                                     CONSTRAINT FK_MESSAGES_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES users (id)
);